#!/system/bin/sh

#if [ -f /data/misc/ipfs/config ];then
#	exit 0;
#else
#	/system/bin/ipfs init;
#fi
if [ -f /data/misc/ipfs/config ];then
	echo "ipfsconfig exist" > /dev/console;
else
	echo "ipfsconfig not exist" > /dev/console;
	/system/bin/ipfs init;
fi
