#!/system/bin/sh

#if [ -f /data/misc/ipfs/config ];then
#	exit 0;
#else
#	/system/bin/ipfs init;
#fi
if [ -f /data/misc/ipfs/config ];then
	echo "Check ipfsconfig exist" > /dev/console;
	/system/bin/ipfs daemon >> /data/misc/ipfs/ipfslog & 
	echo "ipfsdaemon exit"
else
	echo "Check ipfsconfig not exist" > /dev/console;
fi
